FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Use Nginx templates to inject the Railway $PORT variable
COPY nginx.conf /etc/nginx/templates/default.conf.template
ENV PORT=80
CMD ["nginx", "-g", "daemon off;"]
