name: Export Android Project
on:
  workflow_dispatch:

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 📦 Install dependencies
        working-directory: mobile
        run: npm install --legacy-peer-deps

      - name: 🏗 Expo Prebuild
        working-directory: mobile
        run: npx expo prebuild --platform android --non-interactive

      - name: 📦 Zip Android Project
        working-directory: mobile
        run: zip -r android-project.zip android

      - name: 📤 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-source
          path: mobile/android-project.zip
